# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kaddio
email: hello@kaddio.com
description: > # this means to ignore newlines until "baseurl:"
  Kaddio är en webtjänst för psykologer, sjukgymnaster och manuella terapeuter
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kaddio.github.io/kaddio-jekyll" # the base hostname & protocol for your site
twitter_username: kaddioapp
github_username: rhymn
facebook_username: kaddio
linkedin_username: kaddio
instagram_username: kaddioapp

# Build settings
markdown: kramdown

collections:
- guides